#!/bin/bash
set -euo pipefail

# colors
reset=$'\e[m'
green=$'\e[0;32m'
red=$'\e[0;31m'
blue=$'\e[0;34m'

# date format string
_iso8601_fmt="%Y-%m-%dT%H:%M:%S%z"

function log_info() {
    echo "${green}[$(date +"${_iso8601_fmt}")][info]${reset} $1"
}

function log_error() {
    echo "${red}[$(date +"${_iso8601_fmt}")][error]${reset} $1" 1>&2
}

function log_debug() {
    echo "${blue}[$(date +"${_iso8601_fmt}")][debug]${reset} $1"
}
