#!/bin/bash

set -euo pipefail

# TODO: options and usage text

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# TODO: source or make executable and call?
source "${SCRIPT_DIR}"/loggers
source "${SCRIPT_DIR}"/install-module

readonly LOG_FILE="${SCRIPT_DIR}/pave-$(date +%s).log"
touch "${LOG_FILE}"

for module in "${SCRIPT_DIR}"/modules/*; do
    module_name="$(basename "${module}")"
    # echo "[info] Installing module: ${module_name}"
    log_info "Installing module: ${module_name}" | tee -a "${LOG_FILE}"

    # TODO: fail early if module fails to install or continue?
    install_module "${module}" | tee -a "${LOG_FILE}"
done

log_info "Successfully paved machine!" | tee -a "${LOG_FILE}"
