#!/bin/bash

set -euo pipefail

# TODO: options and usage text

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

readonly LOG_FILE="${SCRIPT_DIR}/pave-$(date +%s).log"
touch "${LOG_FILE}"

# walk all dependencies and determine correct order to install modules
ruby "${SCRIPT_DIR}"/pave.rb | tee -a "${LOG_FILE}"
